### ISSUE TITLE
Build fails: error: no matching function for call to '__sort'

### ISSUE THREAD

**Issue by yurivict** [pypr/pysph#152] opened 2018-12-07 07:30 UTC
Fails on FreeBSD 11.2 amd64, clang-60, python-3.6, version 1.0a6:
```
In file included from /usr/include/c++/v1/__string:56:
/usr/include/c++/v1/algorithm:4201:5: error: no matching function for call to '__sort'
    __sort<_Comp_ref>(__first, __last, __comp);
    ^~~~~~~~~~~~~~~~~
pysph/base/nnps_base.cpp:22642:10: note: in instantiation of function template specialization 'std::__1::sort<std::__1::__wrap_iter<std::__1::pair<unsigned int, unsigned
      int> *>, int (std::__1::pair<unsigned int, unsigned int>, std::__1::pair<unsigned int, unsigned int>)>' requested here
    std::sort<std::vector<__pyx_t_5pysph_4base_9nnps_base_id_gid_pair_t> ::iterator,int (__pyx_t_5pysph_4base_9nnps_base_id_gid_pair_t, __pyx_t_5pysph_4base_9nnps_ba...
         ^
/usr/include/c++/v1/algorithm:3998:1: note: candidate function not viable: no known conversion from 'int (*)(std::__1::pair<unsigned int, unsigned int>,
      std::__1::pair<unsigned int, unsigned int>)' to 'int (&)(std::__1::pair<unsigned int, unsigned int>, std::__1::pair<unsigned int, unsigned int>)' for 3rd argument;
      dereference the argument with *
__sort(_RandomAccessIterator __first, _RandomAccessIterator __last, _Compare __comp)
^
1 warning and 1 error generated.
error: command 'cc' failed with exit status 1
```

**Comment by prabhuramachandran** [comment] 2018-12-08 19:59
This looks like a C++ compiler setup issue from the look of it.  I build on OS X with their clang (and also with gcc) but haven't tried on another system with clang.

**Comment by yurivict** [comment] 2018-12-08 20:44
@prabhuramachandran I have clang-6.0.1. What clang did you try on OS X?

**Comment by yurivict** [comment] 2018-12-08 21:02
It builds if in this file/place to remove the ```comparator``` element from the ```std::sort``` template parameters.

**Comment by prabhuramachandran** [comment] 2018-12-10 15:05
@yurivict -- I have this, which seems a bit meaningless `Apple LLVM version 10.0.0 (clang-1000.10.44.4)` .  
Do the tests pass with your modifications?  The additional comparator is needed for one of the calls.  Perhaps there is a better way of doing this?  I will need to investigate this more closely and will do so when I get some time later this week.

**Comment by prabhuramachandran** [comment] 2019-02-05 03:40
@yurivict -- would you be willing to help with this?  I am unable to reproduce the error so am not sure how best to proceed.  Could you please send me the full error message? Thanks.

**Comment by yurivict** [comment] 2019-02-05 03:52
Now it breaks with this message:
```
pyzoltan/core/carray.cpp:44253:3: error: cannot initialize return object of type 'int' with an rvalue of type 'nullptr_t'
  import_array();
  ^~~~~~~~~~~~~~
```
This file appears to be C++ generated from python.

**Comment by prabhuramachandran** [comment] 2019-02-05 04:14
carray is now in its own package called `cyarray` from pypi or here https://github.com/pypr/cyarray.  import_array ought to work as it is used all over the place for numpy, again, if you share the full log -- you can directly email me if you don't want to attach it here.

**Comment by prabhuramachandran** [comment] 2019-02-05 04:21
I am thinking of trying freebsd on a virtual machine, so if you can tell me the steps you followed to perform the installation on a fresh system, that would help.

**Comment by yurivict** [comment] 2019-02-05 05:05
1. Download this ISO image: https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.0/FreeBSD-12.0-RELEASE-amd64-disc1.iso
2. Create a VirtualBox VM with it.
3. While installing it in VM, choose to install the ports collection
4. Boot this VM up
5. Download this shar: https://people.freebsd.org/~yuri/py-PySPH.shar
6. Unpack it while in /usr/ports
7. Go into the port: /usr/ports/science/py-PySPH
8. Type 'make'

It will begin to build the port, and fail with the error above.

**Comment by yurivict** [comment] 2019-02-05 05:06
You can also execute 'pkg install python36' to install it from binary, and prevent its rebuild.

**Comment by prabhuramachandran** [comment] 2019-02-06 19:55
Hi @yurivict -- Thanks for the instructions. I've managed to setup a VM with FreeBSD. 
I've fixed one of the issues in https://github.com/pypr/cyarray/pull/1 
I am able to reproduce your error and see a few more things I can fix.  I hope I should be able to fix it soon.  BTW, I think the package will build fine with gcc but I would like to make sure that it works with clang also.

**Comment by yurivict** [comment] 2019-02-07 02:53
Thanks for fixing the issues. We mostly use clang on FreeBSD.
I will try to create a port again, once you are done.

Yuri

**Closed** 2019-02-08 10:49 UTC

**Comment by prabhuramachandran** [comment] 2019-02-08 10:51
Hi @yurivict -- I've fixed the issues in pysph and compyle.  If you use master of cyarray, compyle and pysph it should work on freebsd with clang.  It should also work fine with openmp.  Please let us know if you run into any other issues.
