### ISSUE TITLE
Trying to use the slider of the interactive plot in 2D removes the widget

### ISSUE THREAD

**Issue by ManosAgelidis** [pypr/pysph#108] opened 2018-07-04 11:33 UTC
Hello,

I am trying to visualize the output of the elliptical_drop_output run within a jupyter notebook with the following code (taken from the docs)

%matplotlib ipympl
from pysph.tools.ipy_viewer import Viewer2D
viewer = Viewer2D('elliptical_drop_output')
viewer.interactive_plot()

This works fine as you can see in the first image 
![image](https://user-images.githubusercontent.com/17083612/42274901-a96d8c64-7f8e-11e8-8376-a8fd8bb9784b.png)

But when I try to use the widget to f.e. select a timeframe the widget is gone and all that is left is the plot. See the picture 
![image](https://user-images.githubusercontent.com/17083612/42274954-c9ddd1f2-7f8e-11e8-9954-4d8a970964db.png)

Any ideas?
 Regards, Manos

**Comment by prabhuramachandran** [comment] 2018-09-14 23:31
I think the ipyml stuff has been in a bit of flux, the jupyter projects change quite fast so this has gone a bit out of date.  We will need to investigate this and fix it.

**Comment by thisisrohan** [comment] 2019-01-25 15:08
@ManosAgelidis could you let us know the version of Python, jupyter, matplotlib and ipympl you're running this on. I ran the same example on Python 3.6.8, jupyter 4.4.0, matplotlib 3.0.2 and ipympl 0.2.1 and could not recreate the issue (check out the screenshots below).
![0](https://user-images.githubusercontent.com/28507927/51753733-953bd400-20e0-11e9-8438-61e479b35870.png)
![1](https://user-images.githubusercontent.com/28507927/51753734-953bd400-20e0-11e9-9b34-e2fffa926aa8.png)

**Comment by prabhuramachandran** [comment] 2019-01-25 17:59
Thanks @thisisrohan, I also tried to reproduce this and it seems to work pretty well for me too.

**Comment by prabhuramachandran** [comment] 2019-02-04 18:43
Closing for now as we are unable to reproduce this.  Please let us know if this is not the case.

**Closed by prabhuramachandran** 2019-02-04 18:43 UTC
