### ISSUE TITLE
Cannot install PySPH on mac with pip no matter what I do

### ISSUE THREAD

**Issue by behzad-vahedi** [pypr/pysph#133] opened 2018-11-05 05:33 UTC
I have been trying to install the package using pip on my mac (OS version 10.13.5) and get an error every time. I have installed gcc, and exported into cc, again error. Exported clang to cc, and again error. What am doing wrong? I am clueless! 

   
$ pip install PySPH    

> 14 warnings and 1 error generated.
>     error: command '/usr/bin/clang' failed with exit status 1
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gy/bjjhbttd565_gbkystqdkm6c0000gn/T/pip-install-gqjbYq/PySPH/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/gy/bjjhbttd565_gbkystqdkm6c0000gn/T/pip-record-v4gXlV/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/gy/bjjhbttd565_gbkystqdkm6c0000gn/T/pip-install-gqjbYq/PySPH/

**Comment by prabhuramachandran** [comment] 2018-11-06 17:31
The version on PyPI is rather old, a new release should be available hopefully in a month but for now can you try this:

```
pip install https://github.com/pypr/pysph/zipball/master
```

Does that work any better?

**Comment by darkknight9394** [comment] 2018-12-08 05:35
I encountered the same problem and have tried the above pip installation. I also tried to install on git clone and pip install pySPH (please see below). When I attempted to run the examples, I got the following error.
# Name                    Version                   Build  Channel
PySPH                     1.0b1.dev0                <pip>

`Traceback (most recent call last):
  File "two_blocks.py", line 8, in <module>
    from pysph.solver.application import Application
  File "/anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/solver/application.py", line 20, in <module>
    from pysph.base.nnps import LinkedListNNPS, BoxSortNNPS, SpatialHashNNPS, \
  File "/anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/base/nnps.py", line 1, in <module>
    from pysph.base.nnps_base import get_number_of_threads, py_flatten, \
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/base/nnps_base.cpython-36m-darwin.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/base/nnps_base.cpython-36m-darwin.so
  Expected in: flat namespace
 in /anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/base/nnps_base.cpython-36m-darwin.so`

**Comment by prabhuramachandran** [comment] 2018-12-08 19:56
Did you install a compiler or a c++ library in your anaconda env?  Can you try in a fresh anaconda environment?  I use pysph all the time on my mac and do not run into this.  I build with both clang (for serial runs) and with gcc-8 via brew with no issues.  One way to see what is going on is to run the following:

`otool -L /anaconda3/lib/python3.6/site-packages/PySPH-1.0b1.dev0-py3.6-macosx-10.7-x86_64.egg/pysph/base/nnps_base.cpython-36m-darwin.so`

and see what it is linking to.  Mine link to 
```
/usr/local/opt/gcc/lib/gcc/8/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
        /usr/local/opt/gcc/lib/gcc/8/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
        /usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

**Comment by prabhuramachandran** [comment] 2020-04-21 19:02
Are you folks still running into these issues?  If not I will close this ticket as I am unable to reproduce this on Linux os MacOS.

**Comment by Stefaniscion** [comment] 2021-04-20 08:32
I've a similar issue

`Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lmkpih7p/pysph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-m_n8_e8i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lmkpih7p/pysph/`

I'm running on a fresh CentOS 8 docker

**Comment by prabhuramachandran** [comment] 2022-02-24 15:22
Is this still resolved, we have tests running on github on Linux, Windows and MacOS so I am not able to reproduce these errors. I am closing this for now, kindly reopen if this persists.

**Closed by prabhuramachandran** 2022-02-24 15:22 UTC
